### ISSUE TITLE
Add export to AVI feature

### ISSUE THREAD

**Issue by EpicLPer** [pbsds/Flipnote-Player#1]
Heya there,

After a bit of search I found this really neat and awesome little tool here and happily said I am so happy that we're now not forced anymore to record the sound via the audio jack :)

However, is it possible to add an "export to AVI" function maybe? Would be awesome since that'd make screen recording the player window unnecessary.

Thanks for a response already!

**Comment by pbsds** [comment]
I have no plans on implementing it, but try asking Austin Burk / Sudofox. He uses a script for converting from the exported images and audio from PPM.py into the videofiles found on sudomemo.net. ;)

**Comment by EpicLPer** [comment]
Hm, sure I can do that :)

Oh, besides: I saw that some flipnotes are not correctly played. As example I tried playing one and on the PC player there was something that looked like "old layers suddenly floating upwards" even tho on the DSi itself the drawing was only shifted to the right.
As example here (watch at 0:04): https://twitter.com/EpicLPer/status/693488836064714752

The character suddenly "ghosts upwards" even tho on the DSi it only shifts to the right without doing this weird effect. This happens on other flipnotes too, probably when they switch to the black background and white color to draw?

**Comment by pbsds** [comment]
That is a known issue, and the program outputs a message everytime it encounters a frame which does that. There's 2 unknown bytes after the frame header which i believe describe how the previous frame should be translated before continued decoding.

**Comment by EpicLPer** [comment]
Will there ever be a fix for this? Kinda sad to see this happening :(

**Comment by pbsds** [comment]
I haven't worked on this for a year, and see little benefit on continuing to work in it.
When Flipnote 3D comes to europe however, it might be possible i'll pick the project back up again, if the format is still used there in one way or the other. :)

**Comment by EpicLPer** [comment]
Flipnote 3D doesn't even have an online section :( So no online community about it anymore as we were used back with Flipnote Studio.

You can already get it on European 3DS's but you need a 3DS able to run homebrew and install CIAs, not sure if you want to go through that route tho :)

**Comment by pbsds** [comment]
I'll stay away from using CIA files for now. But considering i spent a lot of time toying with WAD format for the Wii, i don't know how long that'll last...

**Comment by EpicLPer** [comment]
Using CIAs is nearly as easy (when not even easier) than using WADs on Wii :)
All you need is a 3DS on max. Firmware 10.3, if you've updated beyond that it won't work anymore.
