### ISSUE TITLE
Sudomemo Viewing Broken

### ISSUE THREAD

**Issue by ghost** [pbsds/Flipnote-Player#2]
Due to Austin's recent tightening on security, unauthenticated requests to Sudomemo result in 401.
To fix, add an SID header to requests, with a 40-char SID (A-Z,a-z) value - I suggest using a random one as using one SID will be easy to hit down.

**Comment by pbsds** [comment]
I have thus far used a SID, as you can see [here](https://github.com/pbsds/Flipnote-Player/blob/master/Flipnote%20Player.py#L729).
I've tried changing it to various things, but can't seem to get past the check with this alone. I've tried using both a hexadecimal md5 hash and a 40-char A-Z, a-z string...

**Comment by ghost** [comment]
Perhaps try telling the Player to connect via `ds.sudomemo.net` (the proxy)?
@sudofox may be able to help, however I feel he may not want to :P

**Comment by pbsds** [comment]
It already [does ](https://github.com/pbsds/Flipnote-Player/blob/master/Flipnote%20Player.py#L504)use that [proxy](https://github.com/pbsds/Flipnote-Player/blob/master/config.ini#L8) aswell... I'll try asking Austin about the changes he made.

**Comment by pbsds** [comment]
Seems he blocks when the request has a user-agent. Added a quick fix to this.
