### ISSUE TITLE
Dependency Issues [Win64]

### ISSUE THREAD

**Issue by JoshuaDoes** [pbsds/Flipnote-Player#3]
I have Python 2.7.9 installed on a Windows 10 laptop running on a 64-bit processor. Everything is installed properly (as far as I can tell), however "scikits.samplerate" fails to install. Attached is a log of the failed install attempt. Any help would be greatly appreciated, as it's the last dependency I can't get working.

[error.txt](https://github.com/pbsds/Flipnote-Player/files/994902/error.txt)

**Comment by pbsds** [comment]
I've used the .whl files from [this page](http://www.lfd.uci.edu/~gohlke/pythonlibs/)
Just download the correct file and install with pip
