### ISSUE TITLE
it keeps crashing 

### ISSUE THREAD

**Issue by treesters** [pbsds/Flipnote-Player#4]
once i tried extracting it and opening the exe file, it showed a black screen and closed immediately, giving me a error.txt. i asked my friend if he had the same issue and everything works fine for him. it'd be amazing if you could help.
i have windows 7 and my computer is a 64 bit.

here's a video on what is happening: https://www.youtube.com/watch?v=1cWGxQ8cKVE
error.txt file: [error.txt](https://github.com/pbsds/Flipnote-Player/files/1235251/error.txt)

**Comment by sudofox** [comment]
contents of error.txt:

```
Traceback (most recent call last):
  File "<string>", line 789, in <module>
  File "<string>", line 759, in main
  File "<string>", line 195, in __init__
  File "<string>", line 620, in GotoBrowser
  File "<string>", line 493, in GotoDir
  File "<string>", line 21, in GetDriveNames
UnboundLocalError: local variable 'label' referenced before assignment
```

**Comment by treesters** [comment]
i realize that's what it says, do you have any idea what it means? i'm not too smart with technology.

**Comment by pbsds** [comment]
I found the bug, and pushed a [change](https://github.com/pbsds/Flipnote-Player/commit/dd911c0dc50083ad7c4f0f8901ef64bd36f4dcce) to fix it. I sadly am unable to recompile it with the fixes, because the updated pyinstaller breaks with pygame. Install Python 2.7, install pip, use pip to install pygame, numpy and scikits.resample downloaded from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#scikits.samplerate), then run the file "flipnote player.py" from the newest version of this repo

**Comment by treesters** [comment]
it's still doing the same thing and i've followed your instructions. i have no idea what's going on. :(

**Comment by treesters** [comment]
i slowed down a video where i tried to open flipnote player.py and it said that "PIL wasnt found, image extraction won't work!" and "ImportError: No module named win32api" but for some reason, PIL won't install correctly. i dont even know if i installed anything correctly. :-(

**Comment by treesters** [comment]
ok, so, i keep getting this weird thing where i open that file and it says 

"Warning: PIL not found, image extraction won't work!
win32api error: (21, 'GetVolumeInformation', 'The device is not ready.')
win32api error: (21, 'GetVolumeInformation', 'The device is not ready.')"
but it's open properly and well, but once i click on a flipnote, it crashed. but i did download win32api and PIL so...i'm not too sure what's happening here? 

also, the error.txt file: [error.txt](https://github.com/pbsds/Flipnote-Player/files/1236833/error.txt)

edit: the PIL thing is fixed, i'm still getting the win32api error though,

**Comment by pbsds** [comment]
The win32api errors are expected, but the error you're now getting is because of some behavior that has changed with newer versions of numpy. I've updated the repo with a fix
