### ISSUE TITLE
P-Frame issue

### ISSUE THREAD

**Issue by ethanicus** [pbsds/Flipnote-Player#5]
I don't know if anyone has noticed this. Some animations don't play back properly, usually when little changes from frame to frame. Things such as flickering parts, or artifacts from previous or next frames being laced in with the current one.

**Comment by pbsds** [comment]
This is a known issue, yes. I believe @jaames have a fix for it.
Check out https://github.com/jaames/flipnote.js

**Comment by jaames** [comment]
Yeah, in some cases the previous frame is translated before being merged with the current frame. IIRC, PPM.py doesn't read the translation x and y values correctly, they should be read as two signed 8-bit integers. 

Relevant part of the flipnote.js PPM parser: https://github.com/jaames/flipnote.js/blob/master/src/parser/ppm.js#L258-L261

Relevant part of PPM.py:
https://github.com/pbsds/Flipnote-Player/blob/master/Hatenatools/PPM.py#L299-L308

**Comment by pbsds** [comment]
Should be fixed now, but i'm unable to compile it due to reasons.
I might look into that when i upgrade my wintendo to win10
